use std::fs;
use std::io;
use std::path::Path;

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

/// Every `#[tauri::command]` this app registers in `invoke_handler`.
///
/// Declaring the app manifest makes tauri enforce the ACL on app commands too, so a command that
/// is missing here — or here but not granted by a capability — is rejected at invoke time with
/// nothing on the Rust side to notice. `tests/window_chrome_acl_test.rs` pins both directions.
#[allow(dead_code)]
pub const APP_TAURI_COMMANDS: &[&str] = &[
    "desktop_fetch_update",
    "desktop_install_update",
    "desktop_pick_ssh_identity_file",
    "desktop_get_autostart_enabled",
    "desktop_set_autostart_enabled",
    "desktop_set_tray_state",
    "sync_desktop_pet_overlay_state",
    "desktop_pet_overlay_read_window_state",
    "desktop_pet_overlay_set_input_locked",
    "desktop_pet_overlay_sync_element_metrics",
    "desktop_pet_overlay_start_drag_session",
    "desktop_pet_overlay_apply_drag_delta",
    "desktop_pet_overlay_release_drag_velocity",
    "desktop_pet_overlay_apply_momentum_delta",
    "desktop_pet_overlay_end_drag_session",
    "desktop_pet_overlay_reset_position",
    "emit_desktop_pet_overlay_interaction_result",
    "desktop_pet_overlay_show_main_window",
    "start_system_task",
    "cancel_system_task",
    "get_system_task_snapshot",
    "system_tasks_open_log_path",
    "respond_system_task_prompt",
    "desktop_get_window_chrome_policy",
    "desktop_get_window_state",
    "desktop_minimize_window",
    "desktop_toggle_window_maximize",
    "desktop_close_window",
    "desktop_show_main_window",
    "desktop_start_window_dragging",
    "desktop_finish_shutdown",
];

/// The capability permission that grants `command`, in tauri's autogenerated naming.
#[allow(dead_code)]
pub fn app_command_permission(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SidecarSnapshot {
    pub bytes: Vec<u8>,
    pub unix_mode: Option<u32>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SidecarUpdateAction {
    Noop,
    Copy,
    PermissionsOnly,
    CopyAndPermissions,
}

impl SidecarSnapshot {
    #[allow(dead_code)]
    pub fn from_path(path: &Path) -> io::Result<Self> {
        let bytes = fs::read(path)?;
        Ok(Self {
            unix_mode: read_unix_mode(&fs::metadata(path)?),
            bytes,
        })
    }
}

pub fn resolve_sidecar_update_action(
    source: &SidecarSnapshot,
    destination: Option<&SidecarSnapshot>,
) -> SidecarUpdateAction {
    let Some(destination) = destination else {
        return if source.unix_mode.is_some() {
            SidecarUpdateAction::CopyAndPermissions
        } else {
            SidecarUpdateAction::Copy
        };
    };

    let content_differs = source.bytes != destination.bytes;
    let permissions_differs = source.unix_mode != destination.unix_mode;

    match (content_differs, permissions_differs) {
        (false, false) => SidecarUpdateAction::Noop,
        (true, false) => SidecarUpdateAction::Copy,
        (false, true) => SidecarUpdateAction::PermissionsOnly,
        (true, true) => SidecarUpdateAction::CopyAndPermissions,
    }
}

#[cfg(unix)]
#[allow(dead_code)]
fn read_unix_mode(metadata: &fs::Metadata) -> Option<u32> {
    Some(metadata.permissions().mode())
}

#[cfg(not(unix))]
#[allow(dead_code)]
fn read_unix_mode(_metadata: &fs::Metadata) -> Option<u32> {
    None
}
