# Generated by scripts/pipeline/release/render-homebrew-packages.mjs from cli-v0.2.12; do not edit by hand.
class Happier < Formula
  desc "Run coding agents on your own machines and drive them from any device"
  homepage "https://happier.dev/"
  version "0.2.12"
  license "MIT"

  livecheck do
    url "https://github.com/happier-dev/happier/releases/download/cli-stable/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  on_macos do
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/happier-dev/happier/releases/download/cli-v0.2.12/happier-v0.2.12-darwin-arm64.tar.gz"
      sha256 "e687d32d84af95f6b19a29cf1559f4ebd56b949b3ea0ce76340235039047a576"
    end
    on_intel do
      url "https://github.com/happier-dev/happier/releases/download/cli-v0.2.12/happier-v0.2.12-darwin-x64.tar.gz"
      sha256 "cce41bbcf314b67464dc667bd871ed4f9599da66fa3c6b4292479f9ed0aefd76"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/happier-dev/happier/releases/download/cli-v0.2.12/happier-v0.2.12-linux-arm64.tar.gz"
      sha256 "bfa15e2aa79a6dbd0a714c7e0a6d51be011a43ddde2f4f453d6458b15b430e82"
    end
    on_intel do
      url "https://github.com/happier-dev/happier/releases/download/cli-v0.2.12/happier-v0.2.12-linux-x64.tar.gz"
      sha256 "8978265ce7677bd3f0a0f2f734304bb551452c962b7d46f8f34420892a01fa7e"
    end
  end

  # The payload is a self-contained, signed runtime (compiled `happier` plus the `package-dist`,
  # `node_modules`, `tools` and `scripts` it loads beside itself). Keep it byte-for-byte.
  skip_clean "libexec"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"happier"
  end

  # No `service` block: `happier service install` owns the background service.
  def caveats
    <<~EOS
      Run `happier setup` to connect this computer and sign in.
      Homebrew updates this CLI: use `brew upgrade happier` (`happier self update` defers to it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/happier --version")
  end
end
