export {
  SYSTEM_TASK_PROTOCOL_VERSION,
  SystemTaskEventSchema,
  SystemTaskJsonValueSchema,
  SystemTaskResultErrorSchema,
  SystemTaskResultSchema,
  SystemTaskSpecSchema,
  type SystemTaskEvent,
  type SystemTaskJsonArray,
  type SystemTaskJsonObject,
  type SystemTaskJsonValue,
  type SystemTaskResult,
  type SystemTaskResultError,
  type SystemTaskSpec,
} from './spec.js';

export {
  createTailscaleSecureAccessTaskSpec,
  TAILSCALE_SECURE_ACCESS_SYSTEM_TASK_KIND,
  TAILSCALE_SECURE_ACCESS_SYSTEM_TASK_STEP_IDS,
  type TailscaleSecureAccessInstallPolicy,
  type TailscaleSecureAccessLoginPolicy,
  type TailscaleSecureAccessMode,
  type TailscaleSecureAccessSystemTaskStepId,
  type TailscaleSecureAccessTaskParams,
  type TailscaleSecureAccessTaskResult,
  type TailscaleSecureAccessTaskSpec,
} from './tailscaleSecureAccessTaskContract.js';

export {
  classifySetupPairingRequirement,
  createSetupAccountConsentPromptData,
  createSetupCliChoicePromptData,
  createSetupPairingPromptData,
  createSetupServiceConsentPromptData,
  parseSetupAccountConsentPromptData,
  parseSetupCliChoicePromptData,
  readSetupCliChoiceAnswer,
  parseSetupPairingPromptData,
  parseSetupServiceConsentPromptData,
  setupReplacesValidatedAccount,
  SETUP_ACCOUNT_CONSENT_PROMPT_KIND,
  SETUP_CLI_CHOICE_PROMPT_KIND,
  SETUP_PAIRING_PROMPT_KIND,
  SETUP_SERVICE_CONSENT_PROMPT_KIND,
  SETUP_THIS_COMPUTER_SYSTEM_TASK_KIND,
  type SetupAccountConsentPromptPayload,
  type SetupCliChoice,
  type SetupCliChoicePromptPayload,
  type SetupCliOrigin,
  type SetupCliProvenance,
  type SetupPairingPromptPayload,
  type SetupPairingRequirement,
  type SetupServiceConsentPromptPayload,
  type SetupServiceRuntimeReplacement,
} from './setupThisComputerTaskContract.js';
export {
  CLI_ACQUISITION_PROGRESS_EVENT,
  CliAcquisitionPhaseSchema,
  CliAcquisitionProgressSchema,
  parseCliAcquisitionProgress,
  readCliAcquisitionFailurePhase,
  type CliAcquisitionPhase,
  type CliAcquisitionProgress,
} from './acquisitionProgress.js';
